version: '3.8'

services:
  metalops:
    image: ghcr.io/metalops-dev/web:latest
    networks:
      - proxy
    ports:
      - target: 80
        published: 80
        mode: host
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.metalops-redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.metalops-redirect-https.redirectscheme.permanent=true
      - traefik.http.routers.metalops-http.middlewares=metalops-redirect-https
      - traefik.http.routers.metalops-http.rule=Host(`metalops.com`)
      - traefik.http.routers.metalops-http.entrypoints=http
      - traefik.http.routers.metalops-https.rule=Host(`metalops.dev`)
      - traefik.http.routers.metalops-https.tls.certresolver=letsencrypt
      - traefik.http.routers.metalops-https.tls=true
      - traefik.http.routers.metalops-https.entrypoints=https
      - "traefik.http.services.metalops.loadbalancer.server.port=80"
      - traefik.docker.network=proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # For now only running on single node
      # placement:
      #   constraints:
      #     - node.role == worker


networks:
  proxy:
    external: true
